name:                price-calculator-kata
version:             0.1.0.0
github:              "Cobrijani/price-calculator-kata"
license:             BSD3
author:              "Stefan Bratic"
maintainer:          "cobrijanI@gmail.com"
copyright:           "2019 Stefan Bratic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Cobrijani/price-calculator-kata/blob/master/haskell/README.md>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  price-calculator-kata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - price-calculator-kata

tests:
  price-calculator-kata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - price-calculator-kata
